### ISSUE TITLE
it just crashes plz help

### ISSUE THREAD

**Issue by LittlesectorNZ** [akioweh/EducationPerfected#54]
Error: Requesting main frame too early!
    at assert (C:\Users\SheldonWood\node_modules\puppeteer-core\lib\cjs\puppeteer\util\assert.js:28:15)
    at FrameManager.mainFrame (C:\Users\SheldonWood\node_modules\puppeteer-core\lib\cjs\puppeteer\common\FrameManager.js:162:32)
    at CDPPage.goto (C:\Users\SheldonWood\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Page.js:440:79)
    at C:\Users\SheldonWood\Desktop\e\EducationPerfected-2.1.0\index.js:48:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by akioweh** [comment]
i have no clue...

**Comment by akioweh** [comment]
inactivity
