### ISSUE TITLE
Auto answer not working

### ISSUE THREAD

**Issue by IllNoobis** [akioweh/EducationPerfected#67]
Not working at all. When I try alt + s, it will not start answering,

**Comment by IllNoobis** [comment]
In the console it is showing with"
"There was a parsing error: TypeError: q.DueDate.getTime is not a function
    at AppNotificationParser.parse (AppNotificationsParser.ts:210:42)
    at AppNotificationParser.parseGroup (AppNotificationsParser.ts:253:42)
    at AppNotificationsService.createDisplayableNotifications (AppNotificationService.ts:227:88)
    at BaseNotificationsService.buildDisplayableNotifications (common.js:11420:10)
    at AppNotificationService.ts:67:26"
