### ISSUE TITLE
Error encountered!!

### ISSUE THREAD

**Issue by Ethanjoyce2010** [akioweh/EducationPerfected#78]
Waiting for selector failed: Waiting failed: 30000ms exceeded

TimeoutError: Waiting for selector `#login-username` failed: Waiting failed: 30000ms exceeded
  at WaitTask (internal/path/to/WaitTask.js:50:34)
  at IsolatedWorld.waitForFunction (internal/path/to/Realm.js:25:26)
  at PQueryHandler.waitFor (internal/path/to/QueryHandler.js:170:95)
  at async CdpFrame.waitForSelector (internal/path/to/Frame.js:468:21)
  at async CdpPage.waitForSelector (internal/path/to/Page.js:1309:20)
  at async internal/path/to/index.js:49:13

Node.js v20.13.0

**Comment by akioweh** [comment]
that's when it can't detect the login input boxes... if not user error then fix is easy but out of my effort budget right now
